[project]
name = "Moore_AnimateAnyone"
version = "0.1.0"
description = "My small project"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }